site_name: 饥荒Mod开发速查手册
repo_url: https://github.com/user919lx/dst-qref
theme:
  name: 'material'
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy
    - content.code.annotate
  language: zh
plugins:
  - table-reader
  - search
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  # alternate:
  #   - name: 中文
  #     link: /
  #     lang: zh
  #   - name: English
  #     link: /en/
  #     lang: en
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:xingxing_fisher@163.com
nav:
  - Home: 'index.md'
  - 手册:
    - 系统组件(WIP): 'system_component.md'
    - 组件(WIP): 'component.md'
    - 工具-Util:
      - ModAPI-ModUtil: 'modutil.md'
      - 数学工具-MathUtil: 'mathutil.md'
    - AI:
      - 动作节点: 'brain_action.md'
      - 修饰节点: 'brain_dec.md'
    - 特效(WIP): 'fx.md'
  - About: 'about.md'
  
  
  
